### ISSUE TITLE
Not saving group

### ISSUE THREAD

**Issue by Brodieman** [connormaglynn/save-pinned-tabs-browser-plugin#7]
I am on 0.2.0 from the webstore (yes I know it says to install from git.  I am testing this as a replacement for our teachers who use Saved Pined Tabs which appears to be getting removed by Chrome).  They would not be able to install it anywhere other than the webstore.

When I try to add a group, nothing seems to happen, no group appears.

**Comment by connormaglynn** [comment]
Hi @Brodieman 👋

Thank you for raising the issue! ⭐️

It's not a bug I've come across during my testing of the plugin 🧪

As a first stab at this, I'd suggest ensuring Google Chrome is updated to the latest version 🚀 Since I haven't tested the extension with older versions 🧓

Secondly, if you could go to [chrome://extensions/](chrome://extensions/) in your Chrome browser, you should see the plugin in there - if it's throwing any errors, you should be able to see the details of them there 🚨

<img width="436" alt="image" src="https://github.com/user-attachments/assets/ae2c5a07-9a33-421a-a5eb-a37b7c6cc520">

If you could paste the details of any errors here, I'll make sure to get any issues resolved! 🚀

And do feel free to install it from the Chrome Webstore, the README needs updating 🙈

**Comment by connormaglynn** [comment]
Closing this issue due to it being 3 months stale 📕 

Feel free to re-open it if you can provide additional information! 😁 

There have been several releases since v0.2.0 - so there's a likely chance this is no longer an issue 🚀
